### ISSUE TITLE
Is this a third version??? 🤣 

### ISSUE THREAD

**Issue by Daniel1404** [Nicolas-alt/portafolio-v3#1]
How many versions do you want to build?

**Comment by Nicolas-alt** [comment]
The necessary ones so that at last it is perfect hahaha

**Comment by Daniel1404** [comment]
Why not a single repo with all your portfolio versions?

I mean that's why GitHub branches exist 😅

**Comment by Nicolas-alt** [comment]
That's a good one, however I prefer to keep all split, just for nostalgie

**Comment by Daniel1404** [comment]
:0

Ok that seems a good solution.

Issue solved
